### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'norm_dets'. When using `format_dets` with value `txt`.

### ISSUE THREAD

**Issue by mziai** [laclouis5/globox#45]
**Describe the bug**
Thank you for this awesome tool. There seems to be a bug in cli when specifying `--format_dets txt`. A simple fix may be renaming `norm_in_dets` found [here](https://github.com/laclouis5/globox/blob/290bc25c798606b52ce705c97e4c248c79f6e77a/src/globox/cli.py#L94C1) to `norm_dets` (or vise versa) if I understood the code correctly.

**To Reproduce**
1. Specify `--format_dets txt --norm_dets rel` detection options when using globox cli tool.

**Expected behavior**
No error happens and I can use both `--format_dets txt` and `--norm_dets rel`.

**Environment (please complete the following information):**
 - Ubuntu 22.04 (WSL).
 - Globox version 2.4.3.
 - Python 3.10.12.

**Additional context**
Error traceback:
```shell
Traceback (most recent call last):
  File "/home/user/.local/bin/globox", line 8, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.10/site-packages/globox/cli.py", line 384, in main
    predictions = parse_dets_annotations(args, coco_gts=coco_gts)
  File "/home/user/.local/lib/python3.10/site-packages/globox/cli.py", line 268, in parse_dets_annotations
    relative: bool = args.norm_dets == "rel"
AttributeError: 'Namespace' object has no attribute 'norm_dets'. Did you mean: 'format_dets'?
```

**Comment by laclouis5** [comment]
Thanks for reporting this bug and for the details.

I fixed this issue in the last version 2.4.4.

**Comment by mziai** [comment]
Sorry to bump this closed issue, but as far as I can tell, the problem still persist. What did the trick for me, was changing line 268 from `relative: bool = args.norm_dets == "rel"` to `relative: bool = args.norm_in_dets == "rel"`.

Please correct me if I am wrong, but it is `parse_dets_annotations` function that had to to be modified in this situation, not the `parse_annotations`, as was done in [your fix](https://github.com/laclouis5/globox/commit/7ea8315e6659dfca5adba02ac57bd1cae2adb393). That is because we are dealing with detection format arguments.

@laclouis5

**Comment by laclouis5** [comment]
@mziai Whoops, I did it too fast and updated the wrong line without testing. Could you check if PR #46 solves the issue please ? This reverts the last fix and updates line 268 instead.
